### ISSUE TITLE
Issue with oauth add to team not writing teams.bot part

### ISSUE THREAD

**Issue by alecl** [BeepBoopHQ/beepboop-botkit#8]
Because the teams.bot field is not in place this code fails when the bot tries to process a mention right here:

https://github.com/howdyai/botkit/blob/v0.4.9/lib/SlackBot.js#L177

```
[2017-01-20T03:39:52Z]TypeError: Cannot read property 'user_id' of undefined
[2017-01-20T03:39:52Z] at /usr/src/app/node_modules/botkit/lib/SlackBot.js:177:33
[2017-01-20T03:39:52Z] at Command.callback (/usr/src/app/node_modules/botkit-storage-redis/src/index.js:41:17)
[2017-01-20T03:39:52Z] at normal_reply (/usr/src/app/node_modules/botkit-storage-redis/node_modules/redis/index.js:721:21)
[2017-01-20T03:39:52Z] at RedisClient.return_reply (/usr/src/app/node_modules/botkit-storage-redis/node_modules/redis/index.js:819:9)
[2017-01-20T03:39:52Z] at JavascriptRedisParser.Parser.returnReply (/usr/src/app/node_modules/botkit-storage-redis/node_modules/redis/index.js:192:18)
[2017-01-20T03:39:52Z] at JavascriptRedisParser.execute (/usr/src/app/node_modules/botkit-storage-redis/node_modules/redis/node_modules/redis-parser/lib/parser.js:491:12)
[2017-01-20T03:39:52Z] at Socket.<anonymous> (/usr/src/app/node_modules/botkit-storage-redis/node_modules/redis/index.js:274:27)
[2017-01-20T03:39:52Z] at emitOne (events.js:77:13)
[2017-01-20T03:39:52Z] at Socket.emit (events.js:169:7)
[2017-01-20T03:39:52Z] at readableAddChunk (_stream_readable.js:146:16)
[2017-01-20T03:39:52Z] at Socket.Readable.push (_stream_readable.js:110:10)
[2017-01-20T03:39:52Z] at TCP.onread (net.js:523:20)
```

I'm basically running off of the https://github.com/howdyai/botkit-starter-slack with some conversational and other code added but nothing messing with the core bot experience other than the piece below that runs through beepboop-botkit RTM instead of botkit Events API when running under BeepBoop.

if (process.env.BEEPBOOP) {
 logger.info('Starting in Beep Boop multi-team mode');
 require('beepboop-botkit').start(controller, { debug: true });
} else {
 controller.startTicking();
}

**Slack settings of note**

**OAuth:**
https://beepboophq.com/proxy/:myid/oauth
https://beepboophq.com/api/slack/auth/add-to-slack

_Note, I had to add the second url for direct as apparently "Add to Slack" stops there first before going to the proxy? Was an unexpected surprise._

**Event Subscriptions, Interactive Messages, Slash Commands URL**

https://beepboophq.com/proxy/:myid/slack/receive

**Comment by alecl** [comment]
For the plain botkit side for standalone testing I'm using the Slack Events API and ngrok to tunnel to local machine and followed the instructions [here](https://github.com/howdyai/botkit/blob/master/docs/slack-events-api.md) and all worked fine with the same code.

I'm using https://github.com/howdyai/botkit-storage-redis and a server on RedisLabs.

**Comment by alecl** [comment]
Forgot to mention exception happens on typing something like "Say hi" which loads info from storage. Typing plain "Hi" works.
